name: Fetch Latest Pixiv Bookmark

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC
  workflow_dispatch:    # Allows manual triggering

jobs:
  fetch-bookmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pixivpy3

    - name: Run Pixiv script
      env:
        PIXIV_USERNAME: ${{ secrets.PIXIV_USERNAME }}
        PIXIV_PASSWORD: ${{ secrets.PIXIV_PASSWORD }}
      run: |
        python scripts/fetch_pixiv_bookmark.py

    - name: Commit latest.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add latest.json
        git commit -m "Update latest Pixiv bookmark"
        git push

