name: Generate Video List

on:
  push:
    paths:
      - 'videos/**'
      - '.github/workflows/generate-video-list.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate video list
        run: |
          echo "[" > videoList.json
          for f in videos/*; do
            if [[ "$f" == *.mp4 ]]; then
              name=$(basename "$f")
              echo "  \"$name\"," >> videoList.json
            fi
          done
          sed -i '$ s/,$//' videoList.json
          echo "]" >> videoList.json

      - name: Commit and push video list
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add videoList.json
          git commit -m "Update video list"
          git push
